services:
  web:
    #build: . # For dev builds only
    image: ghcr.io/leinelab/ordertogether
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    env_file:
      - .env
    restart: unless-stopped
